# Generated by Django 3.1.6 on 2021-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shortDescription', models.CharField(max_length=1000)),
                ('mainBody', models.TextField(max_length=20000)),
                ('image1', models.ImageField(upload_to='blog/images/')),
                ('image2', models.ImageField(blank=True, upload_to='blog/images/')),
            ],
        ),
    ]
